In [4]:
import numpy as np
a=np.arange(21)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [5]:
import numpy as np
a=np.arange(0,21,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [18]:
import numpy as np
a=np.arange(3,21,3)
print(a)

[ 3  6  9 12 15 18]


In [17]:
import numpy as np
a=np.arange(1,21,3).reshape(7,1)
print(a)

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.data)

print('list(a): ', list(a))
print('tolist(): ', a.tolist())

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]
 [19]]
2
(7, 1)
7
int32
4
list(a):  [array([1]), array([4]), array([7]), array([10]), array([13]), array([16]), array([19])]
tolist():  [[1], [4], [7], [10], [13], [16], [19]]


In [ ]:
#[簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同
#list只能表層 array可多層